### ISSUE TITLE
automagically wipe (and issue warning) cache file if was generated for a different blocksize

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#36]
I have been messing with block_size (for #29). Now I have some caches spread out generated for a different block size. So we are getting 
```
2021-12-14 11:33:15,827 datalad.fuse.fsspec [DEBUG  ] derivatives/EPIC/sub-I46/sub-I46_ses-MRI_flip-3_VFA.nii.gz: Attempting to open via URL https://api.dandiarchive.org/api/assets/2584be56-e203-4290-91b0-d7bc7b1c81e9/download/ 
Uncaught exception from FUSE operation getattr, returning errno.EINVAL.
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-fuse/venvs/dev3/lib/python3.9/site-packages/fuse.py", line 734, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/yoh/proj/datalad/datalad-fuse/venvs/dev3/lib/python3.9/site-packages/fuse.py", line 774, in getattr
    return self.fgetattr(path, buf, None)
  File "/home/yoh/proj/datalad/datalad-fuse/venvs/dev3/lib/python3.9/site-packages/fuse.py", line 1027, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "/home/yoh/proj/datalad/datalad-fuse/datalad_fuse/fuse_.py", line 54, in __call__
    return super(DataLadFUSE, self).__call__(op, self.root + path, *args)
  File "/home/yoh/proj/datalad/datalad-fuse/venvs/dev3/lib/python3.9/site-packages/fuse.py", line 1076, in __call__
    return getattr(self, op)(*args)
  File "/home/yoh/proj/datalad/datalad-fuse/datalad_fuse/fuse_.py", line 100, in getattr
    fsspec_file = self._adapter.open(path)
  File "/home/yoh/proj/datalad/datalad-fuse/datalad_fuse/fsspec.py", line 206, in open
    return dsap.open(relpath, mode=mode, encoding=encoding, errors=errors)
  File "/home/yoh/proj/datalad/datalad-fuse/datalad_fuse/fsspec.py", line 146, in open
    return self.fs.open(url, mode, **kwargs)
  File "/home/yoh/proj/misc/filesystem_spec/fsspec/implementations/cached.py", line 400, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
  File "/home/yoh/proj/misc/filesystem_spec/fsspec/spec.py", line 1030, in open
    f = self._open(
  File "/home/yoh/proj/misc/filesystem_spec/fsspec/implementations/cached.py", line 400, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
  File "/home/yoh/proj/misc/filesystem_spec/fsspec/implementations/cached.py", line 329, in _open
    raise ValueError(
ValueError: Cached file must be reopened with same blocksize as original (old: 1048576, new 5242880)
```
now without even gaining cleaning idea which cache file to clean up.  I think since playing with blocksize will come back, let's automate just killing that file cache in such cases, and reopening anew.

**Comment by jwodder** [comment]
@yarikoptic How should the code check whether the blocksize differs?  Should it just check the error message for a certain string?

**Comment by yarikoptic** [comment]
yeap, I was thinking of just checking error message, smth like
```
except ValueError as exc:
    if 'must be reopened with same blocksize' in str(exc):
         ...
```
but since we would be using this, I think it would be useful to submit a short PR against fsspec to create a dedicated exception for this purpose so we could avoid matching the message.

**Comment by jwodder** [comment]
@yarikoptic PR submitted to fsspec: https://github.com/fsspec/filesystem_spec/pull/856

**Comment by yarikoptic** [comment]
PR was merged . Filed https://github.com/fsspec/filesystem_spec/issues/876 since I guess we would prefer to have it released right?

**Comment by yarikoptic** [comment]
https://github.com/fsspec/filesystem_spec/issues/876 is resolved -- new release is out, we should be able to use that new exception.

**Comment by jwodder** [comment]
@yarikoptic 

> let's automate just killing that file cache in such cases, and reopening anew

fsspec doesn't have any functionality for deleting the cache for a specific file; we would have to delete the entire cache instead.  Is that acceptable?

**Comment by yarikoptic** [comment]
Hmm, that sucks. Thinking - having accessed GBs of data, and then running into such a file and losing entire cache would suck. Could you check if it is easy to expose needed functionality in fsspec?

**Comment by jwodder** [comment]
@yarikoptic Never mind; it looks like [there is a method for deleting a single cached file](https://github.com/fsspec/filesystem_spec/blob/ece2fe15b1cac41167b31b8421ac9936aef29010/fsspec/implementations/cached.py#L231).
